server:
  port: 8105
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/raze
#    username: postgres
#    password: PostgressAdmin
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    password: aa5992095be8c68e32af26b5d4982081476b12832db24067ef264ddbcb20e924
    url: postgres://pelredfoioyzwd:aa5992095be8c68e32af26b5d4982081476b12832db24067ef264ddbcb20e924@ec2-54-147-36-107.compute-1.amazonaws.com:5432/da9pa4v9dhd43o
    username: pelredfoioyzwd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect